### ISSUE TITLE
func azure functionapp publish 

### ISSUE THREAD

**Issue by dfinke** [Azure/github-actions#52]
Do you have an example github action that uses the Azure Functions Core Tools to publish an Azure function?

https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local

**Comment by ds-ms** [comment]
@vincentdass would you be able to help @dfinke out here?

**Comment by vincentdass** [comment]
@dfinke , currently, the task uses custom node module to deploy functions.
Will be using `function-core-cli-tools` to accomodate Linux consumption app deployments.

**Comment by thesattiraju** [comment]
Closing this issue; as these actions are deprecated now
