### ISSUE TITLE
Why don't publish to the marketplace?

### ISSUE THREAD

**Issue by baruchiro** [Azure/github-actions#53]
https://developer.github.com/marketplace/actions/publishing-an-action-in-the-github-marketplace/

**Comment by JimmyBoh** [comment]
I'm curious about this too. Is there a maintenance cost that's holding it back (update deps, test, re-publish, after each change). Or is it just a low priority task? Could the community help with it?

**Comment by xt0rted** [comment]
Repos with multiple actions can't be published in the marketplace according to the docs at https://developer.github.com/marketplace/actions/publishing-an-action-in-the-github-marketplace/.

> Publishing an action to the GitHub Marketplace requires that the action lives in your public repository's root directory and it exists alone in that repository without other actions.

**Comment by JimmyBoh** [comment]
Thank you for that explanation! I hope future updates to the marketplace will support monorepos!

**Comment by baruchiro** [comment]
What do you say about this:

[https://github.com/marketplace/actions/net-core-cli](https://github.com/marketplace/actions/net-core-cli)

The fork:

[https://github.com/baruchiro/github-actions](https://github.com/baruchiro/github-actions)

**Comment by nikeee** [comment]
Note that there is also [actions/setup-dotnet](https://github.com/actions/setup-dotnet) which installs the .NET Core SDK on the machine instead of running it in a Linux docker container. This allows for running unit tests natively on Windows/Linux/Mac in one build matrix.

**Comment by thesattiraju** [comment]
The majority of the actions here are moved to accommodate the new changes. 
All of them are available in the marketplace.
You can check out the new actions here: https://github.com/azure/actions
